# Generated by Django 5.2.12 on 2026-05-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
